# Generated by Django 5.2.4 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
