# Generated by Django 5.2.4 on 2025-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invitetoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
