// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmY6I9JyaS0IDP1hq7X9aK9f541IF_Fg',
    appId: '1:674284982661:web:a3ddda9cc28c4f5e11b4ec',
    messagingSenderId: '674284982661',
    projectId: 'dukani-4ca16',
    authDomain: 'dukani-4ca16.firebaseapp.com',
    storageBucket: 'dukani-4ca16.firebasestorage.app',
    measurementId: 'G-HR70K17EWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSudm5ihYo1m7u7CpCxlxjgN15Vii3r7g',
    appId: '1:674284982661:android:f325dbd08024f64b11b4ec',
    messagingSenderId: '674284982661',
    projectId: 'dukani-4ca16',
    storageBucket: 'dukani-4ca16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_hFfX6vFPp_v0xT7B_bn_28Kn1g33AI',
    appId: '1:674284982661:ios:1cdf0c6a267e200511b4ec',
    messagingSenderId: '674284982661',
    projectId: 'dukani-4ca16',
    storageBucket: 'dukani-4ca16.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_hFfX6vFPp_v0xT7B_bn_28Kn1g33AI',
    appId: '1:674284982661:ios:1cdf0c6a267e200511b4ec',
    messagingSenderId: '674284982661',
    projectId: 'dukani-4ca16',
    storageBucket: 'dukani-4ca16.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmY6I9JyaS0IDP1hq7X9aK9f541IF_Fg',
    appId: '1:674284982661:web:01e547327a6e9d7011b4ec',
    messagingSenderId: '674284982661',
    projectId: 'dukani-4ca16',
    authDomain: 'dukani-4ca16.firebaseapp.com',
    storageBucket: 'dukani-4ca16.firebasestorage.app',
    measurementId: 'G-RMPQLH5G6K',
  );
}
