// lib/services/auth/fake_auth_service_test.dart

import 'package:flutter_test/flutter_test.dart';
import 'package:mobile_app_flutter/services/auth/fake_auth_service.dart' as fake_auth_service show FakeAuthService, fakeUsers, fakeInvites;
import 'package:mobile_app_flutter/services/auth/i_auth_service.dart'; // Adjust import path
import 'package:mobile_app_flutter/services/auth/local_storage_service.dart'; // Adjust import path
import 'package:mockito/annotations.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mockito/mockito.dart';

import 'fake_auth_service_test.mocks.dart'; // This file will be generated by build_runner

// You might need a more sophisticated setup for `shared_preferences` testing in `test/` directory.
// For now, let's just make sure `LocalStorageService` is cleared.

@GenerateMocks([
  firebase_auth.FirebaseAuth,
  firebase_auth.User,
  FirebaseFirestore,
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  // ADD LocalStorageService HERE
  LocalStorageService,
])
void main() {
  TestWidgetsFlutterBinding.ensureInitialized(); // Required for shared_preferences

  group('FakeAuthService', () {
    late fake_auth_service.FakeAuthService fakeAuthService;
    late MockLocalStorageService mockLocalStorageService;

    setUp(() async {
      mockLocalStorageService =
          MockLocalStorageService(); // Initialize the mock

      // Stub LocalStorageService methods that FakeAuthService will call.
      // Initially, getUserProfile should return null (no logged-in user).
      when(
        mockLocalStorageService.getUserProfile(),
      ).thenAnswer((_) async => null);
      // Stub saveUserProfile and clearUserProfile to do nothing (or return success)
      // since they are async void methods.
      when(
        mockLocalStorageService.saveUserProfile(
          argThat(isA<UserProfile>()) as UserProfile,
        ),
      ).thenAnswer((_) async => Future.value());
      when(
        mockLocalStorageService.clearUserProfile(),
      ).thenAnswer((_) async => Future.value());
      when(
        mockLocalStorageService.saveCurrentShopId(
          argThat(isA<String>()) as String,
        ),
      ).thenAnswer((_) async => Future.value());
      when(
        mockLocalStorageService.getCurrentShopId(),
      ).thenAnswer((_) async => null);

      // Instantiate FakeAuthService using its .test constructor, injecting the mock
      fakeAuthService = fake_auth_service.FakeAuthService.test(
        localStorageService: mockLocalStorageService,
      );

      // Reset fake data before each test to ensure isolation
      // Accessing via the specific import alias (if you named it as `fake_auth_service`)
      fake_auth_service.fakeUsers.clear();
      fake_auth_service.fakeInvites.clear();

      // Populate with initial test data (as needed for your tests)
      fake_auth_service.fakeUsers.addAll({
        "1234567890": UserProfile(
          phoneNumber: "1234567890",
          firstName: "Alice",
          lastName: "Manager",
          profileName: "Alice M.",
          isManager: true,
          shopsOwned: ["shop_A"],
          currentShopId: "shop_A",
        ),
        "0987654321": UserProfile(
          phoneNumber: "0987654321",
          firstName: "Bob",
          lastName: "Worker",
          profileName: "Bob W.",
          isManager: false,
          invitedToShops: ["shop_A"],
          currentShopId: null,
        ),
        "9988776655": UserProfile(
          // Explicitly add invited worker for test
          phoneNumber: "9988776655",
          firstName: "Invited",
          lastName: "Worker",
          profileName: "Invited W.",
          isManager: false,
          invitedToShops: ["shop_A"],
          currentShopId: null,
        ),
      });
      fake_auth_service.fakeInvites.addAll({
        // Ensure the invite is in the fake db
        "9988776655": ["shop_A"],
      });

      // If FakeAuthService's constructor calls _initUser, this line is likely redundant:
      // await service.getLoggedInUser();
      // The service is already initialized using the mocked LocalStorageService.
    });

    test('should send a verification code successfully', () async {
      final success = await fakeAuthService.sendVerificationCode('1234567890');
      expect(success, isTrue);
    });

    test('should log in an existing manager', () async {
      final phoneNumber = '1234567890'; // Existing manager in _fakeUsers
      final result = await fakeAuthService.verifyCode(phoneNumber, '123456');

      expect(result.success, isTrue);
      expect(result.userProfile, isNotNull);
      expect(result.userProfile!.phoneNumber, phoneNumber);
      expect(result.userProfile!.isManager, isTrue);
      expect(result.userProfile!.shopsOwned, ["shop_A"]);

      final loggedInUser = await fakeAuthService.getLoggedInUser();
      expect(loggedInUser, isA<UserProfile>());
      expect(loggedInUser!.phoneNumber, phoneNumber);
    });

    test(
      'should indicate needsProfileCreation for a new invited worker',
      () async {
        final phoneNumber = '9988776655'; // New invited worker in _fakeInvites
        final result = await fakeAuthService.verifyCode(phoneNumber, '123456');

        expect(result.success, isTrue);
        expect(result.needsProfileCreation, isTrue);
        expect(result.isNewUser, isTrue);
        expect(result.userProfile, isNotNull);
        expect(result.userProfile!.phoneNumber, phoneNumber);
        expect(result.userProfile!.invitedToShops, ["shop_A"]);
        expect(result.userProfile!.isManager, isFalse); // Default for new users
      },
    );

    test(
      'should complete profile for a new user and make them a manager',
      () async {
        final phoneNumber = '9998887777'; // Completely new phone number
        await fakeAuthService.verifyCode(phoneNumber, '123456'); // First verification

        final result = await fakeAuthService.completeProfile(
          phoneNumber,
          'New',
          'Manager',
          'NM',
          true,
        );

        expect(result.success, isTrue);
        expect(result.userProfile, isNotNull);
        expect(result.userProfile!.phoneNumber, phoneNumber);
        expect(result.userProfile!.firstName, 'New');
        expect(result.userProfile!.lastName, 'Manager');
        expect(result.userProfile!.profileName, 'NM');
        expect(result.userProfile!.isManager, isTrue);
        expect(
          result.userProfile!.shopsOwned,
          [],
        ); // Should be empty initially for a new manager

        final loggedInUser = await fakeAuthService.getLoggedInUser();
        expect(loggedInUser, isA<UserProfile>());
        expect(loggedInUser!.phoneNumber, phoneNumber);
      },
    );

    test('should allow a worker to accept an invitation', () async {
      final phoneNumber = '0987654321'; // Bob Worker, invited to shop_A
      await fakeAuthService.verifyCode(phoneNumber, '123456'); // Log in Bob

      final result = await fakeAuthService.acceptInvitation(phoneNumber, 'shop_A');

      expect(result.success, isTrue);
      expect(result.userProfile, isNotNull);
      expect(result.userProfile!.shopsOwned, contains('shop_A'));
      expect(
        result.userProfile!.invitedToShops,
        isNot(contains('shop_A')),
      ); // Should be removed from invited
    });

    test('should log out the current user', () async {
      final phoneNumber = '1234567890';
      await fakeAuthService.verifyCode(phoneNumber, '123456');
      expect(await fakeAuthService.getLoggedInUser(), isNotNull);

      await fakeAuthService.logout();
      expect(await fakeAuthService.getLoggedInUser(), isNull);
      expect(
        await mockLocalStorageService.getUserProfile(),
        isNull,
      ); // Verify local storage cleared
    });
  });
}
