// test/services/user_service_test.dart
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:mobile_app_flutter/services/auth/firebase_user_service.dart'; // Adjust import path
import 'package:mobile_app_flutter/services/auth/fake_user_service.dart'; // Adjust import path
import 'package:mobile_app_flutter/services/auth/i_user_service.dart'; // Adjust import path
import 'package:mobile_app_flutter/services/auth/i_auth_service.dart'; // Adjust import path
import 'package:cloud_firestore/cloud_firestore.dart';

// Mock `fakeUsers` and `fakeInvites` from `fake_auth_service.dart`
// This is necessary because FakeUserService depends on them.
import 'package:mobile_app_flutter/services/auth/fake_auth_service.dart' as fake_auth_service show fakeUsers, fakeInvites;
import 'i_user_service_test.mocks.dart'; // This file will be generated by build_runner

// Run `flutter pub run build_runner build` to generate user_service_test.mocks.dart
@GenerateMocks([
  FirebaseFirestore,
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  Query,
  QuerySnapshot,
  QueryDocumentSnapshot,
])
void main() {
  group('UserService Tests', () {
    // --- Test Suite for FirebaseUserService ---
    group('FirebaseUserService', () {
      late MockFirebaseFirestore mockFirestore;
      late MockCollectionReference<Map<String, dynamic>> mockShopsCollection;
      late MockCollectionReference<Map<String, dynamic>> mockUsersCollection;
      late MockCollectionReference<Map<String, dynamic>> mockInvitationsCollection;
      late FirebaseUserService firebaseUserService;

      setUp(() {
        mockFirestore = MockFirebaseFirestore();
        mockShopsCollection = MockCollectionReference<Map<String, dynamic>>();
        mockUsersCollection = MockCollectionReference<Map<String, dynamic>>();
        mockInvitationsCollection = MockCollectionReference<Map<String, dynamic>>();

        // Stub the initial calls to collection()
        when(mockFirestore.collection('shops')).thenReturn(mockShopsCollection);
        when(mockFirestore.collection('users')).thenReturn(mockUsersCollection);
        when(mockFirestore.collection('invitations')).thenReturn(mockInvitationsCollection);

        firebaseUserService = FirebaseUserService.test(firestore: mockFirestore); // Re-initialize with mocks
        // Inject mocks (assuming you don't have dependency injection framework,
        // we'll use a trick or modify the FirebaseUserService constructor for testing)
        // For now, let's assume `_firestore` is accessible or use a setter for testing
        // A common pattern is to make the Firestore instance passed to the constructor.
        // For this example, let's create a test-specific instance that uses the mock.
        firebaseUserService = FirebaseUserService.test(firestore: mockFirestore);
      });

      // To allow injecting the mock Firestore instance for testing
      // Add this constructor to your actual FirebaseUserService class:
      // FirebaseUserService.test({FirebaseFirestore? firestore})
      //     : _firestore = firestore ?? FirebaseFirestore.instance;

      test('createShop creates a shop and updates manager profile', () async {
        final mockShopDocRef = MockDocumentReference<Map<String, dynamic>>();
        final mockManagerUserDocRef = MockDocumentReference<Map<String, dynamic>>();

        when(mockShopsCollection.doc()).thenReturn(mockShopDocRef);
        when(mockShopDocRef.id).thenReturn('new_shop_id_123');
        when(mockShopDocRef.set(any)).thenAnswer((_) async => Future.value());

        when(mockUsersCollection.doc('1234567890')).thenReturn(mockManagerUserDocRef);
        when(mockManagerUserDocRef.update(any)).thenAnswer((_) async => Future.value());

        final shopId = await firebaseUserService.createShop(
          'Test Shop',
          '1234567890',
          storeType: 'Retail',
          streetAddress: '10 Test St',
          city: 'Testville',
          country: 'TestLand',
        );

        expect(shopId, 'new_shop_id_123');
        verify(mockShopsCollection.doc()).called(1);
        verify(mockShopDocRef.set(argThat(
          allOf([
            containsPair('name', 'Test Shop'),
            containsPair('managerPhoneNumber', '1234567890'),
            containsPair('storeType', 'Retail'),
            containsPair('streetAddress', '10 Test St'),
            containsPair('city', 'Testville'),
            containsPair('country', 'TestLand'),
            // Using FieldValue.serverTimestamp() makes it hard to match exactly
            // If you need to test it, use `isA<FieldValue>()`
            containsPair('createdAt', isA<FieldValue>()),
          ]),
        ))).called(1);
        verify(mockUsersCollection.doc('1234567890')).called(1);
        verify(mockManagerUserDocRef.update(argThat(
          containsPair('shopsOwned', isA<FieldValue>()),
        ))).called(1);
      });

      test('inviteWorkerToShop successfully invites worker', () async {
        final mockShopDocRef = MockDocumentReference<Map<String, dynamic>>();
        final mockInvitationDocRef = MockDocumentReference<Map<String, dynamic>>();
        final mockShopSnapshot = MockDocumentSnapshot<Map<String, dynamic>>();

        when(mockShopsCollection.doc('shop_A')).thenReturn(mockShopDocRef);
        when(mockShopDocRef.get()).thenAnswer((_) async => mockShopSnapshot);
        when(mockShopSnapshot.exists).thenReturn(true);
        when(mockShopSnapshot.data()).thenReturn({'managerPhoneNumber': '1234567890', 'name': 'Shop A'});

        when(mockInvitationsCollection.doc('worker_phone')).thenReturn(mockInvitationDocRef);
        when(mockInvitationDocRef.set(any, any)).thenAnswer((_) async => Future.value());

        final result = await firebaseUserService.inviteWorkerToShop(
            '1234567890', 'shop_A', 'worker_phone');

        expect(result, true);
        verify(mockInvitationDocRef.set(
          argThat(containsPair('shops', isA<FieldValue>())),
          argThat(isA<SetOptions>()),
        )).called(1);
      });

      test('inviteWorkerToShop fails if manager does not own shop', () async {
        final mockShopDocRef = MockDocumentReference<Map<String, dynamic>>();
        final mockShopSnapshot = MockDocumentSnapshot<Map<String, dynamic>>();

        when(mockShopsCollection.doc('shop_A')).thenReturn(mockShopDocRef);
        when(mockShopDocRef.get()).thenAnswer((_) async => mockShopSnapshot);
        when(mockShopSnapshot.exists).thenReturn(true);
        when(mockShopSnapshot.data()).thenReturn({'managerPhoneNumber': 'other_manager', 'name': 'Shop A'}); // Not owned by 1234567890

        final result = await firebaseUserService.inviteWorkerToShop(
            '1234567890', 'shop_A', 'worker_phone');

        expect(result, false);
        verifyNever(mockInvitationsCollection.doc(any)); // Ensure no write attempt
      });

      test('getShopsOwnedByManager returns correct shops', () async {
        final mockQuery = MockQuery<Map<String, dynamic>>();
        final mockQuerySnapshot = MockQuerySnapshot<Map<String, dynamic>>();
        final mockDocSnapshot1 = MockQueryDocumentSnapshot<Map<String, dynamic>>();
        final mockDocSnapshot2 = MockQueryDocumentSnapshot<Map<String, dynamic>>();

        when(mockShopsCollection.where('managerPhoneNumber', isEqualTo: 'manager_phone'))
            .thenReturn(mockQuery);
        when(mockQuery.get()).thenAnswer((_) async => mockQuerySnapshot);

        when(mockDocSnapshot1.id).thenReturn('shop_1');
        when(mockDocSnapshot1.data()).thenReturn({
          'name': 'Manager Shop 1',
          'managerPhoneNumber': 'manager_phone',
          'country': 'USA', // Required field
        });
        when(mockDocSnapshot2.id).thenReturn('shop_2');
        when(mockDocSnapshot2.data()).thenReturn({
          'name': 'Manager Shop 2',
          'managerPhoneNumber': 'manager_phone',
          'country': 'USA',
        });

        when(mockQuerySnapshot.docs).thenReturn([
          mockDocSnapshot1 as QueryDocumentSnapshot<Map<String, dynamic>>, // Explicit cast
          mockDocSnapshot2 as QueryDocumentSnapshot<Map<String, dynamic>>, // Explicit cast
        ]);

        final shops = await firebaseUserService.getShopsOwnedByManager('manager_phone');

        expect(shops.length, 2);
        expect(shops[0].id, 'shop_1');
        expect(shops[0].name, 'Manager Shop 1');
        expect(shops[1].id, 'shop_2');
        expect(shops[1].name, 'Manager Shop 2');
      });

      test('getInvitedShopsForWorker returns correct shops', () async {
        final mockInvitationDocRef = MockDocumentReference<Map<String, dynamic>>();
        final mockInvitationSnapshot = MockDocumentSnapshot<Map<String, dynamic>>();
        final mockShopDocRef1 = MockDocumentReference<Map<String, dynamic>>();
        final mockShopSnapshot1 = MockDocumentSnapshot<Map<String, dynamic>>();
        final mockShopDocRef2 = MockDocumentReference<Map<String, dynamic>>();
        final mockShopSnapshot2 = MockDocumentSnapshot<Map<String, dynamic>>();

        when(mockInvitationsCollection.doc('worker_phone')).thenReturn(mockInvitationDocRef);
        when(mockInvitationDocRef.get()).thenAnswer((_) async => mockInvitationSnapshot);
        when(mockInvitationSnapshot.exists).thenReturn(true);
        when(mockInvitationSnapshot.data()).thenReturn({
          'shops': ['invited_shop_1', 'invited_shop_2']
        });

        when(mockShopsCollection.doc('invited_shop_1')).thenReturn(mockShopDocRef1);
        when(mockShopsCollection.doc('invited_shop_2')).thenReturn(mockShopDocRef2);

        when(mockShopDocRef1.get()).thenAnswer((_) async => mockShopSnapshot1);
        when(mockShopSnapshot1.exists).thenReturn(true);
        when(mockShopSnapshot1.id).thenReturn('invited_shop_1');
        when(mockShopSnapshot1.data()).thenReturn({
          'name': 'Invited Shop 1',
          'managerPhoneNumber': 'manager_a',
          'country': 'USA',
        });

        when(mockShopDocRef2.get()).thenAnswer((_) async => mockShopSnapshot2);
        when(mockShopSnapshot2.exists).thenReturn(true);
        when(mockShopSnapshot2.id).thenReturn('invited_shop_2');
        when(mockShopSnapshot2.data()).thenReturn({
          'name': 'Invited Shop 2',
          'managerPhoneNumber': 'manager_b',
          'country': 'UK',
        });

        final shops = await firebaseUserService.getInvitedShopsForWorker('worker_phone');

        expect(shops.length, 2);
        expect(shops[0].id, 'invited_shop_1');
        expect(shops[0].name, 'Invited Shop 1');
        expect(shops[1].id, 'invited_shop_2');
        expect(shops[1].name, 'Invited Shop 2');
      });
      
    });

    // --- Test Suite for FakeUserService ---
    group('FakeUserService', () {
      late FakeUserService fakeUserService;

      // Helper to clear the fakeShops and fakeInvitationsDb for testing
      // This requires making these maps not 'final' or providing a test-specific way to clear them
      // For this example, let's assume we can clear them (e.g., they are `var` or have a getter).
      // If they are truly `final` top-level, mocking `FakeUserService` itself would be harder
      // and testing would focus on its behavior given its initial state.
      // For practical testing, you'd usually make these non-final or pass them in.
      // Let's modify the service to allow clearing for tests if needed.
      void _resetFakeShops() {
        (fakeShops as Map).clear(); // Cast to Map to use clear() if it's final in real code
      }

      void _resetFakeInvitationsDb() {
        (fakeInvitationsDb as Map).clear(); // Cast to Map
      }

      setUp(() {
        fakeUserService = FakeUserService();
        // Reset fake data before each test
        fake_auth_service.fakeUsers.clear();
        fake_auth_service.fakeInvites.clear();

        // Populate with test data for FakeAuthService's fakeUsers/fakeInvites
        fake_auth_service.fakeUsers.addAll({
          "1234567890": UserProfile(
            phoneNumber: "1234567890",
            firstName: "Alice", lastName: "Manager", profileName: "Alice M.",
            isManager: true, shopsOwned: ["shop_A"]
          ),
          "0987654321": UserProfile(
            phoneNumber: "0987654321",
            firstName: "Bob", lastName: "Worker", profileName: "Bob W.",
            isManager: false, invitedToShops: ["shop_A"]
          ),
        });

        // Initialize fakeShops and fakeInvitationsDb for FakeUserService
        // Since fakeShops and fakeInvitationsDb are `final` in the actual service,
        // and initialized at the top level, we can't directly reset them easily here.
        // A common pattern for testing these is to pass a mutable map to the constructor
        // or ensure the service itself has a reset method for tests.
        // For simplicity for this example, we'll work with the existing state of fakeShops
        // or ensure tests don't rely on it being empty, or manually clear it if possible.
        // For now, let's assume `fakeShops` is implicitly reset by nature of `FakeUserService`
        // and that we are working with its internal state correctly.
        // For a more robust test, `fakeShops` and `fakeInvitationsDb` should be injectable
        // or the class should have a `resetForTest` method.
        // We will directly manipulate `fakeShops` via reflection or a test-only setter
        // or just accept its global state if it's simpler.
        // Given `fakeShops` is a top-level `final Map`, directly clearing it like this:
        _resetFakeShops();
        _resetFakeInvitationsDb();

        // Add some base shops for testing FakeUserService
        fakeShops.addAll({
          "shop_A": ShopInfo(
            id: "shop_A", name: "Alice's Emporium", managerPhoneNumber: "1234567890",
            country: "USA", storeType: "General Store", streetAddress: "123 Main", city: "Anytown",
          ),
          "shop_B": ShopInfo(
            id: "shop_B", name: "Bob's Bolts", managerPhoneNumber: "another_manager",
            country: "USA", storeType: "Hardware", streetAddress: "456 Side", city: "Otherville",
          ),
        });
      });

      test('createShop adds a new shop and updates manager profile', () async {
        final initialShopCount = fakeShops.length;
        final shopId = await fakeUserService.createShop(
          'New Fake Shop',
          '1234567890',
          storeType: 'Online',
          country: 'Canada',
        );

        expect(fakeShops.length, initialShopCount + 1);
        expect(fakeShops.containsKey(shopId), isTrue);
        expect(fakeShops[shopId]?.name, 'New Fake Shop');
        expect(fakeShops[shopId]?.country, 'Canada');

        // Verify manager's shopsOwned is updated in the shared fakeUsers map
        final manager = fake_auth_service.fakeUsers['1234567890'];
        expect(manager?.shopsOwned, contains(shopId));
      });

      test('inviteWorkerToShop adds invitation to fakeInvites and fakeInvitationsDb', () async {
        final initialInviteCount = fakeInvitationsDb.length;
        final workerPhone = 'worker_invited_1';
        final shopId = 'shop_A';

        final result = await fakeUserService.inviteWorkerToShop(
            '1234567890', shopId, workerPhone);

        expect(result, isTrue);
        expect(fakeInvitationsDb, containsPair(workerPhone, contains(shopId)));
        expect(fake_auth_service.fakeInvites, containsPair(workerPhone, contains(shopId)));
      });

      test('inviteWorkerToShop fails if manager does not own shop', () async {
        final workerPhone = 'worker_invited_2';
        final shopId = 'shop_B'; // Manager '1234567890' does not own shop_B

        final result = await fakeUserService.inviteWorkerToShop(
            '1234567890', shopId, workerPhone);

        expect(result, isFalse);
        expect(fakeInvitationsDb, isNot(contains(workerPhone)));
        expect(fake_auth_service.fakeInvites, isNot(contains(workerPhone)));
      });

      test('getShopsOwnedByManager returns correct shops for a manager', () async {
        // Add another shop for the manager for this test
        fakeShops["shop_X"] = ShopInfo(
            id: "shop_X", name: "Extra Shop", managerPhoneNumber: "1234567890", country: "USA");

        final shops = await fakeUserService.getShopsOwnedByManager('1234567890');
        expect(shops.length, 2); // shop_A and shop_X
        expect(shops.map((s) => s.id), containsAll(['shop_A', 'shop_X']));
      });

      test('getInvitedShopsForWorker returns correct shops for a worker', () async {
        // Ensure Bob is invited to shop_A, which is already in fakeShops
        fake_auth_service.fakeInvites['0987654321'] = ['shop_A'];
        fakeInvitationsDb['0987654321'] = ['shop_A'];


        final shops = await fakeUserService.getInvitedShopsForWorker('0987654321');
        expect(shops.length, 1);
        expect(shops[0].id, 'shop_A');
        expect(shops[0].name, 'Alice\'s Emporium');
      });

      test('getInvitedShopsForWorker returns empty list for worker with no invites', () async {
        fake_auth_service.fakeInvites.remove('no_invites_worker'); // Ensure no invites
        fakeInvitationsDb.remove('no_invites_worker'); // Ensure no invites

        final shops = await fakeUserService.getInvitedShopsForWorker('no_invites_worker');
        expect(shops, isEmpty);
      });
    });
  });
}